fivem:
  image: fivem-server

  stdin_open: true
  tty: true

  volumes:
    # You must provide a server config file
    - ./server.cfg:/srv/server.cfg

    # You must clone from https://github.com/citizenfx/cfx-server-data
    - ./cfx-server-data/resources:/srv/resources
    - ./cfx-server-data/cache:/srv/cache

  ports:
    - "30120:30120/tcp"
    - "30120:30120/udp"
