
local cfg = {}

-- define each group with a set of permissions
-- _config property:
--- gtype (optional): used to have only one group with the same gtype per player (example: a job gtype to only have one job)
--- onspawn (optional): function(player) (called when the player spawn with the group)
--- onjoin (optional): function(player) (called when the player join the group)
--- onleave (optional): function(player) (called when the player leave the group)
--- (you have direct access to vRP and vRPclient, the tunnel to client, in the config callbacks)

cfg.groups = {
  ["superadmin"] = {
    _config = {onspawn = function(player) vRPclient.notify(player,{"Você é um ~b~SuperAdministrador."}) end},
    "player.group.remove",
    "player.group.add",
    "player.givemoney",
    "player.giveitem",
	"player.blips",
  },
  ["admin"] = {
	_config = {onspawn = function(player) vRPclient.notify(player,{"Você é um ~b~Administrador."}) end},
    "admin.tickets",
    "admin.announce",
    "player.list",
    "player.whitelist",
    "player.unwhitelist",
    "player.kick",
    "player.ban",
    "player.unban",
    "player.noclip",
    "player.custom_emote",
    "player.custom_sound",
    "player.display_custom",
    "player.coords",
    "player.tptome",
	"admin.deleteveh",
	"admin.spawnveh",
	"admin.godmode",
	"player.tptowaypoint",
	"admin.easy_unjail",
	"admin.spikes",
    "player.tpto"
  },
  ["moderador"] = {
    _config = {onspawn = function(player) vRPclient.notify(player,{"Você é um ~b~Moderador."}) end},
	"player.whitelist",
	"player.unwhitelist",
    "player.tptome",
    "player.list",
    "player.kick",
    "player.tpto",
	"player.tptowaypoint",
	"player.group.remove",
    "player.group.add",
  },   
  ["vipdima"] = {
    _config = {onspawn = function(player) vRPclient.notify(player,{"Você é um ~b~VIP Dima."}) end},
	"garagem.vipdima",
  },
  ["vipgold"] = {
    _config = {onspawn = function(player) vRPclient.notify(player,{"Você é um ~y~VIP Gold."}) end},
	"garagem.vipgold",
  },   
  ["vipprata"] = {
    _config = {onspawn = function(player) vRPclient.notify(player,{"Você é um ~h~VIP Prata."}) end},
	"garagem.vipprata",
  },   
  ["vipbronze"] = {
    _config = {onspawn = function(player) vRPclient.notify(player,{"Você é um ~o~VIP Bronze."}) end},
	"garagem.vipbronze",
  },   
  -- the group user is auto added to all logged players
  ["user"] = {
    "player.phone",
	"player.loot",
	"player.store_armor",
	"player.fix_haircut",
    "player.player_menu",
    "player.store_money",
    "player.store_weapons",
    "player.check",
	"coma.skipper",
	"coma.caller",
    "player.calladmin",
	"emergency_heal",
    "police.seizable",
  }, 

--POLÍCIA MILITAR (RADIO PATRULHA)
["Recruta PMESP"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rp.cloakroom",
    "police.pc",
	"rp.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"recruta.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[PMERJ] - Soldado"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
	"ft.garagem",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "gate.cloakroom",
    "police.pc",
	"GATE.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"recruta.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[PMERJ] - Comandante"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "gate.cloakroom",
    "police.pc",
	"gate.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"recruta.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["Soldado PMESP"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rp.cloakroom",
    "police.pc",
	"rp.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"soldado.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["Cabo PMESP"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rp.cloakroom",
    "police.pc",
	"rp.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"cabo.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["Sargento PMESP"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rp.cloakroom",
    "police.pc",
	"rp.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"psargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},
["Tenente PMESP"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rp.cloakroom",
    "police.pc",
	"rp.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"ptenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["Capitão PMESP"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rp.cloakroom",
    "police.pc",
	"rp.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"capitao.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[POLÍCIA MILITAR] - Major"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rp.cloakroom",
    "police.pc",
	"rp.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"major.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[POLÍCIA MILITAR] - Tenente Coronel"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rp.cloakroom",
    "police.pc",
	"rp.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"tcoronel.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[POLÍCIA MILITAR] - Coronel"] = {
    _config = {gtype = "job"},
    
	"n3.pm.armas",
	"boss_lspd.pc",
    
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rp.cloakroom",
    "police.pc",
	"rp.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"coronel.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},
--FORÇA TÁTICA
["[FORÇA TÁTICA] - Recruta"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"recruta.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - Soldado"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"soldado.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - Cabo"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"cabo.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - 3º Sargento"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"tsargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - 2º Sargento"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"ssargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - 1º Sargento"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"psargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - Subtenente"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"subtenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - Aspirante"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"aspirante.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - 2º Tenente"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"stenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - 1º Tenente"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"ptenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - Capitão"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"capitao.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - Major"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"major.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - Tenente Coronel"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"tcoronel.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[FORÇA TÁTICA] - Coronel"] = {
    _config = {gtype = "job"},
    
	"n3.pm.armas",
	"boss_lspd.pc",
    
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "ft.cloakroom",
    "police.pc",
	"ft.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"coronel.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},
--ROCAM
["[ROCAM] - Recruta"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"recruta.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - Soldado"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"soldado.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - Cabo"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"cabo.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - 3º Sargento"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"tsargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - 2º Sargento"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"ssargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - 1º Sargento"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"psargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - Subtenente"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"subtenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - Aspirante"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"aspirante.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - 2º Tenente"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"stenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - 1º Tenente"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"ptenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - Capitão"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"capitao.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - Major"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"major.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - Tenente Coronel"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"tcoronel.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROCAM] - Coronel"] = {
    _config = {gtype = "job"},
    
	"n3.pm.armas",
	"boss_lspd.pc",
    
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rocam.cloakroom",
    "police.pc",
	"rocam.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"coronel.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},
--ROTA
["[ROTA] - Recruta"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"recruta.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROTA] - Soldado"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"soldado.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROTA] - Cabo"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"cabo.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROTA] - 3º Sargento"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"tsargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROTA] - 2º Sargento"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"ssargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROTA] - 1º Sargento"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"psargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROTA] - Subtenente"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"subtenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROTA] - Aspirante"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"aspirante.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROTA] - 2º Tenente"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"stenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROTA] - 1º Tenente"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"ptenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROTA] - Capitão"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"capitao.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROTA] - Major"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"major.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[ROTA] - Tenente Coronel"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"tcoronel.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["Comandante ROTA"] = {
    _config = {gtype = "job"},
    
	"n3.pm.armas",
	"boss_lspd.pc",
    
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "rota.cloakroom",
    "police.pc",
	"rota.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"coronel.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},
--GRPAe
["[GRPAe] - Recruta"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"recruta.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[GRPAe] - Soldado"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"soldado.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[GRPAe] - Cabo"] = {
    _config = {gtype = "job"},
	"n1.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"cabo.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[GRPAe] - 3º Sargento"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"tsargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[GRPAe] - 2º Sargento"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"ssargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[GRPAe] - 1º Sargento"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"psargento.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[GRPAe] - Subtenente"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"subtenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[GRPAe] - Aspirante"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"aspirante.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[GRPAe] - 2º Tenente"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"stenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[GRPAe] - 1º Tenente"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
	"emergency.revive",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"ptenente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["Águia PMESP"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"capitao.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[GRPAe] - Major"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"major.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[GRPAe] - Tenente Coronel"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"tcoronel.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},

["[GRPAe] - Coronel"] = {
    _config = {gtype = "job"},
    
	"n3.pm.armas",
	"boss_lspd.pc",
    
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "grpae.cloakroom",
    "police.pc",
	"grpae.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"coronel.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},
--POLÍCIA CIVIL
["[Delegado da Policia Civil"] = {
    _config = {gtype = "job"},
	"n3.pm.armas",
	"boss_lspd.pc",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "pcivil.cloakroom",
    "police.pc",
	"pcivil.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"delegado.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},
["Delegada da Policia Civil"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
	"boss_lspd.pc",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "pcivil.cloakroom",
    "police.pc",
	"pcivil.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"perito.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},
["[POLÍCIA CIVIL] - Investigador"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
	"boss_lspd.pc",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "pcivil.cloakroom",
    "police.pc",
	"pcivil.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"investigador.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},
["Agente da Policia Civil"] = {
    _config = {gtype = "job"},
	"n2.pm.armas",
	"boss_lspd.pc",
    "player.list",
	"admin.spikes",
	"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu",
	"hotkey.handcuff",
    "pcivil.cloakroom",
    "police.pc",
	"pcivil.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
	"policia.assalto",
    "police.announce",
	"police.askid",
	"agente.paycheck",
	"mission.police.transfer",
    "mission.police.patrol",	
    "-police.store_weapons",
    "-police.seizable"
},
--SAMU
  ["Samu "] = {
    _config = { gtype = "job" },
    "emergency.revive",
    "emergency.shop",
	"emergency_heal",
    "emergency.service",
	"hospital.garagem",
	"emergency.medkit",
	"csocorrista.paycheck",
	"mission.emergency.transfer",
	"samu.uniforme",
	"coma.caller",
  },
  ["Samu Lider"] = {
    _config = { gtype = "job" },
    "emergency.revive",
    "emergency.shop",
	"emergency_heal",
    "emergency.service",
	"hospital.garagem",
	"emergency.medkit",
	"dhospital.paycheck",
	"mission.emergency.transfer",
	"coma.caller",
	"samu.uniforme",
  },
  
  ["Mecânico"] = {
    _config = { gtype = "job"},
    "vehicle.repair",
    "vehicle.replace",
	"repair.paycheck",
	"mission.repair.satellite_dishes",
	"mission.repair.wind_turbines",
    "repair.service",
	"repair.garagem",
  },
  
  ["Minerador de Diamante"] = {
    _config = { gtype = "job"},
    "veiculo.minerador",
	"minerar",
	"minerador.uniforme",
	"processar.diamante",
	"vender.diamante",
  },
--GARI
["Gari"] = {
    _config = { 
      gtype = "job",
    },
    "missao.gari.coleta",
	"gari.veiculo",
	"gari.paycheck",
	"gari.uniforme",
	"gari.coleta",
	"gari.reciclagem",

},
--CORREIOS
["Correios"] = {
    _config = { 
      gtype = "job",
    },
    "missao.correios.coleta",
	"correios.veiculo",
	"sedex.permissao",
	"correios.paycheck",
	"delivery.gopostal",
	"correios.pacote",
	"correios.uniforme",
},
  
  ["UBER"] = {
    _config = { gtype = "job" },
    "UBER.service",
	"UBER.paycheck",
	"uber.uniforme",
	"mission.UBER.passenger",
	"UBER.garagem",
	"UBER.paycheck",
  },

  ["Lenhador"] = {
    _config = { gtype = "job" },
    "coletar.lenha",
	"vender.lenha",
	"veiculo.lenhador",
  },
  ["UberEATS"] = {
    _config = { gtype = "job" },
	"delivery.paycheck",
	"delivery.service",
    "mission.delivery.food",
	"delivery.garagem",
  },
  ["Ladrão de Carros"] = {
    _config = { gtype = "job" },
    "mission.carjack.vehicle"
  },
  ["Assassino Profissional"] = {
    _config = { gtype = "job" },
	"hitman.takebounty",
    "-hitman.addbounty",
	"-player.blips",
	"mission.hitman"
  },
  ["Hacker"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,{"Ae parça, já que tu é hacker, instala minha impressora?."}) end	},
	"-player.blips",
	"mission.delivery.card",
	"hacker.credit_cards",
	"hacker.hack"
  },
  ["Ladrão"] = {
    _config = { gtype = "job" },
	"-player.blips",
	"mugger.mug"
  },
  ["Advogado"] = {
    _config = { gtype = "job" },
	"carteira.oab",
  },  
  ["[AMMUNATION] - Empresario"] = {
  _config = { gtype = "job" },
    "empresarioArmas.loadshop",
    "empresarioArmas.vehicle",
	"empresarioArmas.lavagem",
	"empresarioArmas.cloakroom",
    "empresarioArmas.paycheck"
  },
    ["[AMMUNATION] - Sócio"] = {
	_config = {onspawn = function(player) vRPclient.notify(player,{"Você é sócio da ~b~Ammunation Gun Club"}) end},
    "empresarioArmas.loadshop",
    "empresarioArmas.vehicle",
	"empresarioArmas.lavagem",
	"empresarioArmas.cloakroom",
  },
  ["[P.D.M.] - Sócio"] = {
	_config = {onspawn = function(player) vRPclient.notify(player,{"Você é sócio da ~b~Premium Deluxe Motorsport"}) end},
	"empresarioC.revenda",
	"empresarioC.cloakroom",
	"empresarioC.lavagem",
  },
  ["Transportador de Valores"] = {
    _config = { gtype = "job" },
	"mission.bankdriver.moneybank",
	"bankdriver.vehicle",
	"bankdriver.paycheck",
	"tvalores.uniforme",
	"bankdriver.money"
  },  
  ["Pescador"] = {
    _config = { gtype = "job" },
	"pescador.veiculo",
	"pescador.uniforme",
	"pescador.pesca",
  },
  ["Jornalista"] = {
    _config = { gtype = "job" },
	"jornalista.veiculo",
	"jornalista.uniforme",
	"jornalista.salario",
  },
  ["Cameraman"] = {
    _config = { gtype = "job" },
	"jornalista.veiculo",
	"jornalista.uniforme",
	"cameraman.salario",
  },
  ["[Facção] - Líder"] = {
    _config = { gtype = "job" },
	"comprar.drogas",
  },
  ["[Facção] - Membro"] = {
    _config = { gtype = "job" },
	"comprar.drogas",
  },
  ["Traficante de Drogas"] = {
    _config = { gtype = "job" },
	"comprar.drogas",
	"vender.drogas.maconha",
	"vender.drogas.cocaina",
	"vender.drogas.metanfetamina",
  },

  ["Traficante de Animais"] = {
    _config = { gtype = "job" },
	"contrabando.tartaruga",
  },
  ["Mafia Chefe"] = {
    _config = { gtype = "job" },
	"fabricar.armas",
	"comprar.armas",
	"comprar.drogas",
	"vender.drogas.maconha",
	"vender.drogas.cocaina",
	"vender.drogas.metanfetamina",
  },
  ["Mafia  Braço Direito"] = {
    _config = { gtype = "job" },
	"fabricar.armas",
	"comprar.drogas",
	"vender.drogas.maconha",
	"vender.drogas.cocaina",
	"vender.drogas.metanfetamina",
  },
  ["Contrabandista"] = {
    _config = { gtype = "job" },
	"comprar.muambeiro",
	"comprar.cigarro",
	"vender.muambeiro",
	"vender.cigarro",
  },
  ["Traficante de Órgãos"] = {
    _config = { gtype = "job" },
	"coletar.orgao",
	"vender.orgao",
  },
  ["Desempregado"] = {
    _config = { gtype = "job" },
	"bolsafamilia.paycheck",
  }
}

-- groups are added dynamically using the API or the menu, but you can add group when an user join here
cfg.users = {
  [1] = { -- give superadmin and admin group to the first created user on the database
    "superadmin",
    "admin"
  }
}

-- group selectors
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {
  ["~o~Agencia de Empregos"] = {
    _config = {x = -268.3537902832, y = -957.37261962891, z = 31.223134994507, blipid = 351, blipcolor = 47},
	"UBER",
	"Advogado",
	"Transportador de Valores",
    "Mecânico",
	"UberEATS",
	"Minerador de Diamante",
	"Lenhador",
    "Gari",
	"Correios",
	"Pescador",
	"Desempregado"
  },
  ["~r~Empregos Ilegais"] = {
    _config = {x = 707.324462890625, y = -966.986511230469, z = 30.4128551483154, blipid = 351, blipcolor = 1},
	"Ladrão de Carros",
	"Hacker",
	"Traficante de Drogas",
	"Traficante de Animais",
	"Contrabandista",
	"Traficante de Órgãos",
  },
}

return cfg

